name: Generate Snake Game
# ... (configuração padrão baseada em {Link: Platane/snk https://github.com/marketplace/actions/snake-game-generator-from-github-contributions})
on:
  schedule:
    - cron: "0 */12 * * *" # Atualiza a cada 12 horas
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        # ... configurações de usuário e saída
